"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { usePathname } from "next/navigation";
import BottomNav from "./components/navbar/BottomNav";
import { QueryClient, QueryClientProvider } from "react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname(); // 현재 경로를 가져옵니다.

  // // '/diary' 경로에서는 헤더를 숨기고, 그 외에는 표시
  // const showHeader = pathname !== "/add";

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryClientProvider client={queryClient}>
          <BottomNav />
          <div className="pages">{children}</div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
